# Generated by Django 5.2.3 on 2025-06-28 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book_app', '0002_delete_fine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='isbn',
        ),
    ]
