# Generated by Django 5.2.3 on 2025-06-29 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book_app', '0006_remove_member_address_alter_book_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='copies_available',
            field=models.CharField(default=3),
        ),
        migrations.AlterField(
            model_name='book',
            name='copies_total',
            field=models.CharField(default=3),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_year',
            field=models.CharField(blank=True, null=True),
        ),
    ]
