# Generated by Django 5.2.3 on 2025-07-15 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book_app', '0007_alter_book_copies_available_alter_book_copies_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='copies_available',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='book',
            name='copies_total',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_year',
            field=models.CharField(blank=True, null=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
