# Generated by Django 5.2.3 on 2025-07-15 04:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book_app', '0008_alter_book_copies_available_alter_book_copies_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='copies_available',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='book',
            name='copies_total',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='due_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='loan',
            name='return_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(max_length=10),
        ),
    ]
