# Generated by Django 5.2.3 on 2025-07-15 05:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book_app', '0010_alter_book_copies_available_alter_book_copies_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='return_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
