# Generated by Django 5.2.3 on 2025-07-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book_app', '0011_alter_loan_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='copies_available',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='book',
            name='copies_total',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='due_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(default='borrowed', max_length=10),
        ),
    ]
