# Generated by Django 5.2.3 on 2025-07-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book_app', '0014_alter_loan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='due_date',
            field=models.DateField(),
        ),
    ]
